// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder - in production, generate using: protoc --go_out=. --go_opt=paths=source_relative pkg/protocol/message.proto

package protocol

// Placeholder types - replace with actual generated code
type ControlMessage struct {
	Type    MessageType
	NodeID  string
	RoomID  string
	Payload interface{}
}

type MessageType int32

const (
	MessageTypeJoinRequest      MessageType = 0
	MessageTypeJoinResponse     MessageType = 1
	MessageTypeStatusUpdate     MessageType = 2
	MessageTypeRoleAssignment   MessageType = 3
	MessageTypeStreamAssignment MessageType = 4
	MessageTypeHealthCheck      MessageType = 5
	MessageTypeError            MessageType = 6
	MessageTypeLeave            MessageType = 7
)

type JoinRequest struct {
	UserID       string
	RoomID       string
	Capabilities NodeCapabilities
}

type JoinResponse struct {
	Success        bool
	NodeID         string
	RoomID         string
	ParticipantIDs []string
	InitialRole    Role
	Streams        []StreamInfo
}

type StatusUpdate struct {
	Metrics     NodeMetrics
	CanForward  bool
	CurrentRole Role
}

type NodeMetrics struct {
	BandwidthMbps      float64
	CPUUsagePercent    float64
	MemoryUsagePercent float64
	RTTMs              int64
	PacketLossPercent  float64
	Timestamp          int64
}

type NodeCapabilities struct {
	CanForward           bool
	MaxForwardingStreams int32
	MinBandwidthMbps     float64
}

type RoleAssignment struct {
	Role            Role
	Reason          string
	AssignedStreams []StreamInfo
}

type Role int32

const (
	RoleReceiver  Role = 0
	RoleForwarder Role = 1
	RoleHybrid    Role = 2
)

type StreamAssignment struct {
	StreamID      string
	SourceNodeID  string
	TargetNodeIDs []string
	StreamType    StreamType
	IsForwarding  bool
}

type StreamType int32

const (
	StreamTypeAudio      StreamType = 0
	StreamTypeVideo      StreamType = 1
	StreamTypeAudioVideo StreamType = 2
)

type StreamInfo struct {
	StreamID     string
	SourceNodeID string
	StreamType   StreamType
	SDPOffer     string
	SDPAnswer    string
}

type HealthCheck struct {
	Healthy bool
	Message string
}

type ErrorMessage struct {
	Code    string
	Message string
}
